#!/bin/csh

set uwbin = uw-testbin

# Single process
sys161 -c sys161-8MB.conf kernel "p $uwbin/vm-stack1;q"
echo "-----------"
sys161 -c sys161-8MB.conf kernel "p $uwbin/vm-stack2;q"
echo "-----------"

exit 0


