#!/bin/csh

set uwbin = uw-testbin
set pgm = $uwbin/vm-mix1-fork
set config = "-c sys161-2MB.conf"
set run = "sys161 $config kernel" 

$run "p $pgm;q"
echo "-----------"
# This test takes too long
# $run "p $pgm; p $pgm; p $pgm ;q"
# echo "-----------"


